# Generated by Django 5.1.6 on 2025-03-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='due',
            name='next_reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
