# Generated by Django 5.1.6 on 2025-02-26 17:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expensesplit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expenses',
            new_name='Expense',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='amounts',
            new_name='amount',
        ),
    ]
