# Generated by Django 5.1.6 on 2025-02-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensesplit', '0003_rename_title_group_name_transaction_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
        migrations.AddField(
            model_name='group',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
