# Generated by Django 5.1.6 on 2025-02-28 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expensesplit', '0004_remove_transaction_description'),
        ('expensesplit', '0004_remove_transaction_description_group_completed'),
    ]

    operations = [
    ]
