# Generated by Django 5.1.6 on 2025-03-04 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('interest_rate', models.FloatField()),
                ('max_loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_credit_score', models.IntegerField()),
                ('tenure', models.IntegerField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('GOLD', 'Gold Loan'), ('BUSINESS', 'Business Loan'), ('EDUCATION', 'Education Loan'), ('CAR', 'Car Loan'), ('PERSONAL', 'Personal Loan'), ('HOME', 'Home Loan')], default='PERSONAL', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
